version: 2
jobs:
  build:
    docker:
      - image: zedtux/docker-rubocop
    working_directory: ~/app
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: apt-get update && apt-get install -y cmake

      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: run pronto
          command: pronto run -f github_pr_review -c origin/master
